### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by JeroRoque** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-JeroRoque#1]
[Infografía_de_calidad_Jeronima_Roque.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-JeroRoque/files/15463514/Infografia_de_calidad_Jeronima_Roque.pdf)

**Comment by josealfredo79** [comment]
Calificacion 20
